# Generated by Django 5.0.2 on 2024-03-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number_user_phone_number_area_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number_area_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario'), ('driver', 'Conductor')], default='user', max_length=16),
        ),
    ]
