# Generated by Django 5.0.2 on 2024-04-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_phone_number_area_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
