# Generated by Django 5.0.2 on 2024-04-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_dislikes_user_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonorificTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='honorific_titles',
            field=models.ManyToManyField(to='users.honorifictitle'),
        ),
    ]
