# Generated by Django 5.0.2 on 2024-04-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_honorifictitle_user_honorific_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='honorific_titles',
            field=models.ManyToManyField(blank=True, to='users.honorifictitle'),
        ),
    ]
