# Generated by Django 5.0.2 on 2024-03-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_remove_ride_route_remove_riderequest_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('started', 'Iniciado'), ('finished', 'Finalizado'), ('canceled', 'Cancelado')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('started', 'Iniciado'), ('finished', 'Finalizado'), ('canceled', 'Cancelado')], default='pending', max_length=16),
        ),
    ]
